name: Auto Update Blog

on:
  schedule:
    - cron: '*/30 * * * *'  # 30分ごと
  workflow_dispatch:  # 手動実行も可能

permissions:
  contents: write

jobs:
  update-blog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install httpx python-dotenv aiofiles
    
    - name: Generate new article with full review
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        TZ: 'Asia/Tokyo'
      run: |
        python generate_article_with_full_review.py || echo "Article generation with full review completed"
    
    - name: Commit and push if changed
      env:
        TZ: 'Asia/Tokyo'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --staged --quiet || git commit -m "Auto-update: New articles $(date +'%Y-%m-%d %H:%M JST')"
        git push